"""
Which systemd units are NOT well, from a reply Forge already fetched.

WHERE THIS CAME FROM

Read off /traces on 2026-09-15, five real sysadmin turns. One of them
was "Aucune erreur sur mon Deck ?" -- and it was answered from CPU, RAM,
containers and kernel logs, with not one unit state in the context,
because no collector produced any.

Meanwhile _discover_node had been calling busctl ListUnits on every run
since August and `_parse_busctl_units` kept `row[0]` and dropped the
rest. The D-Bus signature is a(ssssssouso) and its fourth field is
`active_state`: the answer to "is anything failing?" was arriving in the
same reply, every time, and being thrown away.

WHY A FAILED COUNT AND NOT A LIST OF EVERYTHING

522 units on this machine, four of every eight names being `.device`
noise. A context carrying all of them would spend its whole budget
saying that nothing is wrong, and the run already costs 35 to 83
seconds, essentially all of it model time (0.6 s of it is every
collector and both discovery commands put together, measured on the
same traces). So what goes in is what a question about errors is asking
for: how many units are not running as they should, and which.

`failed_count` is emitted even when it is zero, for the reason
`container.running_count` is: zero failures OBSERVED is an answer, and
an absence of facts is not. It is the difference between "nothing is
wrong" and "nobody looked", which is the whole point of this package.

WHY ITS OWN busctl CALL

_discover_node runs the same command one node earlier and this does not
reuse its output, exactly as ContainersCollector does not reuse
`running_containers()`. A collector that took someone else's list would
inherit that list's failure modes silently -- and that list is built by
a function that returns names only. One extra proxied D-Bus call against
a local socket, inside a step that costs 0.6 s.
"""

from datetime import datetime

from forge.config import SYSADMIN_DISCOVERY_TIMEOUT
from forge.harnais.collector import CostHint, Observation
from forge.harnais.facts import Fact
from forge.harnais.host_exec import (
    UNIT_ACTIVE_STATE,
    UNIT_NAME,
    UNIT_SUB_STATE,
    discover_units_cmd,
    parse_units,
)
from forge.harnais.host_exec import run_fixed as _run_fixed

_ERROR_PREFIX = "[error]"

#: The states a unit can sit in without anything being wrong.
#:
#: `active` is running, `inactive` is a unit that ran and finished (a
#: one-shot, a completed job) or was never started. Neither is news.
#: Everything else is: `failed` is the one people mean, and
#: `activating` / `deactivating` caught at rest -- which is what a
#: restart loop looks like from here, and what both host proxies did
#: for three days in September while nothing said so.
_UNREMARKABLE = frozenset({"active", "inactive"})

#: Generated by udev because a device node exists. It cannot fail and
#: cannot be restarted, so it can only add noise to a count of things
#: that are wrong. Same rule and same reason as
#: graphs.sysadmin._UNLOGGED_UNIT_SUFFIX, which drops them from what a
#: user is shown.
_NOT_A_HEALTH_QUESTION = ".device"


class SystemUnitsCollector:
    name = "units"
    domains = ("unit",)

    def is_available(self) -> bool:
        # Same posture as ContainersCollector: "can busctl reach the
        # bus?" cannot be answered without asking it, and asking it is
        # collect(). A cheap pre-check would either lie or run the
        # command twice.
        return True

    def cost_hint(self) -> CostHint:
        return "moderate"

    def collect(self) -> Observation:
        at = datetime.now()  # noqa: DTZ005 -- local time, same as context_info
        raw = _run_fixed(discover_units_cmd(), SYSADMIN_DISCOVERY_TIMEOUT)

        if raw.startswith(_ERROR_PREFIX):
            return Observation.failure(self.name, self.domains, raw, at)

        try:
            rows = parse_units(raw)
        except (ValueError, KeyError, IndexError, TypeError) as e:
            # busctl answered with something this does not recognise.
            # A shape we cannot read is a failed observation, never a
            # shorter list -- the same rule the containers collector
            # follows, and the reason systemctl's failure message once
            # became two units called "System" and "Failed".
            return Observation.failure(
                self.name,
                self.domains,
                f"[error] could not read busctl ListUnits output: {e}",
                at,
            )

        unwell = [
            row
            for row in rows
            if not str(row[UNIT_NAME]).endswith(_NOT_A_HEALTH_QUESTION)
            and str(row[UNIT_ACTIVE_STATE]) not in _UNREMARKABLE
        ]

        facts = [Fact("unit", "failed_count", len(unwell), None, at, self.name)]
        for row in unwell:
            # The entity is in the key because Fact has no field for
            # it (section 4 of the design), same as the containers
            # collector. Value carries both states because they answer
            # different questions: `failed` says it gave up,
            # `activating` with sub `auto-restart` says it is looping.
            facts.append(
                Fact(
                    "unit",
                    f"{row[UNIT_NAME]}.state",
                    f"{row[UNIT_ACTIVE_STATE]} ({row[UNIT_SUB_STATE]})",
                    None,
                    at,
                    self.name,
                )
            )
        return Observation.of(self.name, self.domains, facts, at)
