"""
The unit domain, and the reply it was already being sent.

"Aucune erreur sur mon Deck ?" was asked in production on 2026-09-14 and
answered from CPU, RAM, containers and kernel logs -- with not one unit
state in the context, because no collector produced any.

busctl ListUnits had been running on every sysadmin turn since August,
and its D-Bus signature is a(ssssssouso): field 3 is `active_state`.
graphs.sysadmin._parse_busctl_units kept field 0 and dropped the rest,
so the answer to "is anything failing?" arrived in the same reply every
time and was thrown away.

The cost of reading it is in the budget, not the clock: the same traces
put every collector and both discovery commands together at 0.6 s of a
35-to-83-second run. What a context cannot afford is 522 units saying
nothing is wrong, which is why only what is NOT well goes in.
"""

import pytest

from forge.harnais.collectors import units as units_mod
from forge.harnais.collectors.units import SystemUnitsCollector


def _reply(*rows) -> str:
    """A busctl --json=short ListUnits reply, in its real shape."""
    body = ",".join(
        f'["{name}","","loaded","{active}","{sub}","","/",0,"","/"]'
        for name, active, sub in rows
    )
    return f'{{"type":"a(ssssssouso)","data":[[{body}]]}}'


def _collect(monkeypatch, raw):
    monkeypatch.setattr(units_mod, "_run_fixed", lambda cmd, t: raw)
    return SystemUnitsCollector().collect()


def _facts(observation) -> dict:
    return {f.key: f.value for f in observation.facts}


class TestWhatGoesIn:
    def test_a_failed_unit_is_named_with_both_its_states(self, monkeypatch):
        """
        Both, because they answer different questions: `failed` says it
        gave up, and `activating (auto-restart)` says it is looping --
        which is what both host proxies did for three days in September
        while nothing reported it.
        """
        observation = _collect(
            monkeypatch,
            _reply(
                ("forge.service", "active", "running"),
                ("cups.service", "failed", "failed"),
            ),
        )

        facts = _facts(observation)
        assert facts["failed_count"] == 1
        assert facts["cups.service.state"] == "failed (failed)"
        assert "forge.service.state" not in facts

    def test_a_restart_loop_counts_as_not_well(self, monkeypatch):
        facts = _facts(
            _collect(
                monkeypatch,
                _reply(("forge-podman-ro-proxy.service", "activating", "auto-restart")),
            )
        )

        assert facts["failed_count"] == 1
        assert (
            facts["forge-podman-ro-proxy.service.state"] == "activating (auto-restart)"
        )

    @pytest.mark.parametrize("state", ["active", "inactive"])
    def test_a_unit_at_rest_is_not_news(self, monkeypatch, state):
        """
        `inactive` is a one-shot that finished or a unit nobody
        started. Reporting either would fill the context with 500 lines
        saying nothing is wrong.
        """
        facts = _facts(_collect(monkeypatch, _reply(("x.service", state, "dead"))))

        assert facts == {"failed_count": 0}

    def test_device_units_never_count(self, monkeypatch):
        """
        Generated by udev because a device node exists: it cannot fail
        and cannot be restarted. Same rule and same reason as
        graphs.sysadmin._UNLOGGED_UNIT_SUFFIX.
        """
        facts = _facts(
            _collect(monkeypatch, _reply(("dev-sda.device", "activating", "tentative")))
        )

        assert facts == {"failed_count": 0}


class TestZeroIsAnObservation:
    def test_a_healthy_machine_still_says_so(self, monkeypatch):
        """
        The count exists even at zero, for the reason
        container.running_count does: "nothing is failing" is an
        answer, and an absence of facts is not one. Observation refuses
        a successful run with no facts precisely so this cannot be
        forgotten.
        """
        observation = _collect(
            monkeypatch, _reply(("forge.service", "active", "running"))
        )

        assert not observation.failed
        assert _facts(observation) == {"failed_count": 0}

    def test_an_empty_machine_is_not_a_failure(self, monkeypatch):
        observation = _collect(monkeypatch, '{"type":"a","data":[[]]}')

        assert not observation.failed
        assert _facts(observation) == {"failed_count": 0}


class TestWhenItCannotLook:
    def test_busctl_failing_is_an_observation_failure_not_zero(self, monkeypatch):
        """
        The distinction this whole package exists for. A dead D-Bus
        proxy must not read as "nothing is failing" -- which is exactly
        what a bare count would have said during the three-day outage.
        """
        observation = _collect(
            monkeypatch, "[error] busctl exited 1: Failed to connect to bus"
        )

        assert observation.failed
        assert "Failed to connect to bus" in observation.error
        assert observation.facts == ()

    @pytest.mark.parametrize(
        "raw",
        [
            "not json at all",
            '{"type":"a"}',  # no data
            '{"type":"a","data":[]}',  # data, but no row array
        ],
    )
    def test_a_shape_it_cannot_read_fails_rather_than_counting_zero(
        self, monkeypatch, raw
    ):
        """
        A reply this does not recognise is a failed observation, never
        a shorter list. The same rule the containers collector follows,
        and the reason systemctl's own failure text once became two
        units called "System" and "Failed".
        """
        observation = _collect(monkeypatch, raw)

        assert observation.failed
        assert "could not read busctl" in observation.error

    def test_a_row_shorter_than_the_signature_is_dropped(self, monkeypatch):
        """
        Not padded. A tuple that is not the shape this was verified
        against is not a unit anyone should read a state off -- reading
        index 3 of a short row would be an IndexError at best and
        someone else's field at worst.
        """
        observation = _collect(
            monkeypatch, '{"type":"a","data":[[["short.service","failed"]]]}'
        )

        assert not observation.failed
        assert _facts(observation) == {"failed_count": 0}


def test_it_asks_busctl_through_the_configured_proxy(monkeypatch):
    """
    Asserted on the command, not the mock: the collector must build it
    with harnais.host_exec.discover_units_cmd, so SYSADMIN_DBUS_ADDRESS
    still points it at the filtered proxy rather than the host bus.
    """
    from forge.harnais import host_exec

    monkeypatch.setattr(host_exec, "SYSADMIN_DBUS_ADDRESS", "unix:path=/run/p/bus")
    seen = {}

    def capture(cmd, timeout):
        seen["cmd"] = cmd
        return '{"type":"a","data":[[]]}'

    monkeypatch.setattr(units_mod, "_run_fixed", capture)
    SystemUnitsCollector().collect()

    assert seen["cmd"][0] == "busctl"
    assert "--address=unix:path=/run/p/bus" in seen["cmd"]
    assert "ListUnits" in seen["cmd"]


def test_a_failed_unit_reaches_the_rendered_context(monkeypatch):
    """
    The payoff, end to end: the question that was asked in production
    now has something to be answered from.

    Note what sits beside it. A unit looping on `auto-restart` and the
    domain it breaks appear in the same context, one as a fact and one
    as an unobserved reading naming the socket -- cause and consequence,
    which is the three-day outage of September in two lines.

    Aspirational for those two units specifically: they are systemd
    `--user` units and deploy/forge-dbus-proxy.sh exposes the SYSTEM
    bus, so they are invisible to this collector by construction. A
    system-level service failing the same way is not.
    """
    from forge import harnais
    from forge.harnais.collectors import containers as containers_mod
    from forge.harnais.collectors import cpu_ram as cpu_ram_mod
    from forge.harnais.collectors import logs as logs_mod
    from forge.kernel.context_builder import ContextBuilder, fact_claims
    from forge.kernel.world_model import InMemoryWorldModel

    monkeypatch.setattr(
        units_mod,
        "_run_fixed",
        lambda cmd, t: _reply(
            ("forge.service", "active", "running"),
            ("cups.service", "failed", "failed"),
        ),
    )
    monkeypatch.setattr(
        containers_mod, "_run_fixed", lambda cmd, t: "[error] podman: socket gone"
    )
    monkeypatch.setattr(
        cpu_ram_mod,
        "_read",
        lambda p: (
            "MemTotal: 15160368 kB\nMemAvailable: 900480 kB\n"
            if p == cpu_ram_mod._MEMINFO
            else "7.80 6.12 5.44 1/1594 2759\n"
        ),
    )
    monkeypatch.setattr(logs_mod, "_run_fixed", lambda cmd, t: "kernel: amdgpu")

    world = InMemoryWorldModel()
    for observation in harnais.observe(harnais.default_collectors()):
        world.record_observation(observation)
    context = ContextBuilder(world).build_for("Aucune erreur sur mon Deck ?", 1400)

    claims = fact_claims(context)
    assert any("unit.cups.service.state" in c and "failed" in c for c in claims)
    assert any("unit.failed_count = 1" in c for c in claims)
    # and the healthy one is not there, so the count is the signal
    assert not any("forge.service.state" in c for c in claims)
