"""
Forge sysadmin graph: discover -> collect -> synthesize.

Same reasoning as graphs/research.py: a deterministic fixed sequence,
never a router-driven multi-step chain. The router makes exactly ONE
decision (call "sysadmin"), the graph itself decides what to run next
-- no mid-flow judgment call is ever handed back to the model.

Security model (read-only, always):
  - discover_node runs two fixed, parameter-free commands
    (a busctl ListUnits call, podman ps) -- nothing here can be
    influenced by user input, so there is no injection surface at
    this step.
  - collect_node only ever runs a command built from a fixed template
    (see _COLLECT_TEMPLATES) whose one variable slot (a unit or
    container name) must appear verbatim in the list discover_node
    just returned. A name that isn't in that list is refused before
    any subprocess is started -- this is the entire threat model:
    nothing reaches subprocess.run() that wasn't independently
    confirmed to already exist on the system, and no shell=True is
    ever used, so there is no string-interpolation-into-a-shell
    surface either.
  - No mutation command exists in this module, at all. Restarting or
    stopping anything is explicitly out of scope for v3.11 -- this
    graph only ever reads logs and proposes; see the module docstring
    in tools/sysadmin.py for the human-in-the-loop reasoning, the
    same one already applied to tools/git.py staying read-only.

Nodes:
  discover_node    -- lists active systemd units and podman containers
  collect_node      -- fetches logs for one validated target (or
                        kernel logs as a fallback when no target was
                        named or found)
  synthesize_node   -- single LLM call producing a diagnosis and a
                        proposed fix, never an executed action

`.device` units never reach any of it: discovery drops them, because
a unit generated by udev has no journal of its own and is not a target
anyone can name on purpose. It is also what the user was reading --
four of the eight names shown in eighteen real runs were device nodes,
under a sub-step that called them `services`.

Three nodes written entirely in code refuse instead, and each exists
because a model, handed evidence about something else, answered
fluently anyway: target_missed (the named target is in neither list),
collect_failed (the command errored), nothing_collected (the command
returned no lines).

THE FOURTH CASE IS THE ONE THAT IS STILL OPEN, and it has now been
measured rather than assumed. Logs are collected before anyone reads
the question -- that is what makes the question answerable -- so they
may simply not contain the answer. The prompt says so and asks the
model to say so plainly; when it complies the reply is prose, which
forge/non_answer.py cannot match and the run does not report, so the
exchange is stored as though it were a diagnosis.

The obvious fix is a verdict the code can read. bench/sysadmin_verdict.py
asked for one four ways, over eight fixtures whose answer is known, on
2026-09-12:

    arm       right  FALSE NO  FALSE YES
    plain         5         0          3
    negated       5         3          0
    cite          5         0          3
    reason        3         3          2

Read the two error columns, not the first one. `plain` ("do these logs
answer?") is wrong only in the YES direction; `negated` (the same
question inverted) is wrong only in the NO direction. Each arm answers
the SHAPE of the question it was asked and gets right exactly the
fixtures where that shape happens to be correct. `cite`, which had to
name the line that answers and could have said NONE, never chose NONE
where it had the option -- it took line 1 in six cases of seven. And
`plain` said YES about an EMPTY log block, which is what
nothing_collected now refuses without asking anyone.

So there is no verdict channel here at this model size, in any of the
four shapes, and one deterministic case was hiding inside the idea.

Edges:
  discover_node  -> collect_node     (always)
  collect_node   -> synthesize_node  (always -- a failed individual
                                       collection still gets surfaced
                                       to the model as "[error] ...",
                                       it isn't fatal to the run)

Usage (Python):
  from forge.graphs.sysadmin import run
  print(run(target_hint="searxng", question="pourquoi ça redémarre ?"))
"""

import difflib
import json
import subprocess

from forge import harnais, lang, non_answer, subtrace
from forge.config import (
    ENFORCE_ANSWER_LANGUAGE,
    SYSADMIN_COLLECT_TIMEOUT,
    SYSADMIN_CONTEXT_BUDGET_TOKENS,
    SYSADMIN_DBUS_ADDRESS,
    SYSADMIN_DISCOVERY_TIMEOUT,
    SYSADMIN_JOURNAL_DIR,
    SYSADMIN_LOG_CHARS_BUDGET,
    SYSADMIN_MAX_LOG_LINES,
    SYSADMIN_PODMAN_URL,
    SYSADMIN_USE_HARNAIS,
)
from forge.context_info import today_line
from forge.errors import ProviderError
from forge.graph import Graph
from forge.kernel.context_builder import MVP_DOMAINS, ContextBuilder
from forge.kernel.world_model import InMemoryWorldModel
from forge.llm import call_llm
from forge.logger import log
from forge.text_cleaning import (
    looks_like_a_copy,
    strip_think_blocks,
    try_unwrap_router_json,
)
from forge.types import AgentState

_MAX_SYNTHESIS_OUTPUT_CHARS = 4000

# Same reasoning as graphs/review.py and graphs/research.py: this
# model needs the exact shape it must NOT produce shown explicitly.
# _PROMPT_LEAK_MARKERS catches the model echoing the INSTRUCTION
# markers themselves (rare). _EXAMPLE_LEAK_FRAGMENT catches the
# actually-observed failure mode: the model silently copying the
# GOOD ANSWER *content* verbatim, without ever echoing the marker
# word -- caught in production on 2026-08-11, where a question about
# a completely different container ("forge-llm") got this exact
# fabricated searxng/port-8888 text back as if it were a real
# diagnosis. A distinctive fragment of the example is enough: an
# unrelated real diagnosis coincidentally using this exact phrase is
# effectively impossible.
_PROMPT_LEAK_MARKERS = [
    "Respond in plain text",
    "GOOD ANSWER:",
    "NEVER DO THIS",
]
_EXAMPLE_LEAK_FRAGMENTS = [
    "port 8888 est déjà occupé",  # previous example, kept as a permanent safety net
    "exemple-service.service",
    "manquant.conf",
]


# Fixed, parameter-free discovery commands. Functions, not static
# lists: SYSADMIN_DBUS_ADDRESS/SYSADMIN_PODMAN_URL let these target a
# filtered proxy instead of the raw host bus/socket -- see config.py's
# comment above these three env vars, and deploy/README.md for the
# proxies themselves. Empty (default, incl. every test in this file)
# means "unchanged": no proxy configured, no extra flag added, exact
# same command as before this was made configurable.
def _DISCOVER_UNITS_CMD() -> list[str]:
    # `systemctl list-units` was the original approach but had to be
    # abandoned: confirmed in production (SYSTEMD_LOG_LEVEL=debug)
    # that systemctl hardcodes a connection attempt at
    # /run/systemd/private first -- a systemd-specific shortcut
    # protocol, NOT standard D-Bus -- and never falls back to
    # DBUS_SYSTEM_BUS_ADDRESS (or any other address) if that exact
    # path is unavailable, which it always is inside a container whose
    # PID 1 isn't systemd. `busctl` has no such quirk: it speaks
    # standard D-Bus and honors --address correctly, confirmed
    # repeatedly against the same filtered proxy that systemctl
    # refused to use. --json=short gives a real parseable structure
    # (see _parse_busctl_units) instead of the columnar text
    # `systemctl list-units` produces.
    cmd = ["busctl", "--json=short"]
    if SYSADMIN_DBUS_ADDRESS:
        cmd.append(f"--address={SYSADMIN_DBUS_ADDRESS}")
    return cmd + [
        "call",
        "org.freedesktop.systemd1",
        "/org/freedesktop/systemd1",
        "org.freedesktop.systemd1.Manager",
        "ListUnits",
    ]


#: The one unit type discovery drops, and the reason it is a suffix
#: test rather than a list of types to keep.
#:
#: A `.device` unit is generated by udev because a device node exists.
#: It cannot fail, cannot be restarted, and writes nothing of its own
#: to the journal -- `journalctl -u <x>.device` is empty by
#: construction -- so it is not an answer to any question this graph
#: can be asked, and it is not a target anyone can name on purpose.
#:
#: Measured in the real traces, eighteen runs between 2026-08-11 and
#: 2026-08-22, all reporting 522 units: **four of the eight names the
#: user is shown are `.device`**, and they are the longest ones,
#: carrying systemd's hex escapes --
#: `dev-disk-by\x2dpath-pci\x2d0000:01:00.0\x2dnvme\x2d1\x2dpart-by\x2dpartlabel-var\x2dA.device`.
#: The sub-step called them `services`.
#:
#: Every other type stays. A `.mount` that failed, a `.timer` that did
#: not fire, a `.socket` nothing is listening on are all real
#: questions with real journal entries behind them, and a rule that
#: kept only `.service` would refuse them to save a second line of
#: code.
_UNLOGGED_UNIT_SUFFIX = ".device"


def _loggable(units: list[str]) -> list[str]:
    """The discovered units that could answer a question about logs."""
    return [u for u in units if not u.endswith(_UNLOGGED_UNIT_SUFFIX)]


def _parse_busctl_units(raw: str) -> list[str]:
    """ListUnits' D-Bus signature is a(ssssssouso) -- an array of
    10-field tuples (name, description, load_state, active_state,
    sub_state, following, unit_path, job_id, job_type, job_path).
    `busctl --json=short` wraps that as {"type": "...", "data": [rows]}
    where `data[0]` is the array of tuples and each tuple's index 0 is
    the unit name -- verified against real output in production
    before writing this, not guessed from the D-Bus spec alone."""
    parsed = json.loads(raw)
    rows = parsed["data"][0]
    return [row[0] for row in rows if row]


def _DISCOVER_CONTAINERS_CMD() -> list[str]:
    base = ["podman"]
    if SYSADMIN_PODMAN_URL:
        base += ["--url", SYSADMIN_PODMAN_URL]
    return base + ["ps", "--format", "{{.Names}}"]


def running_containers() -> list[str]:
    """
    The container names podman reports, or [] if it cannot be asked.

    Published rather than inlined in _discover_node because a second
    caller needs the same list for a different reason:
    graphs/research.py asks whether a question it just searched the web
    for was about one of these. Two readings of `podman ps` would drift
    the day the command grows a flag.

    Empty on any failure, which is the only safe answer here -- a
    caller cannot tell "no containers" from "the proxy is down" and
    must not act as though it could.
    """
    raw = _run_fixed(_DISCOVER_CONTAINERS_CMD(), SYSADMIN_DISCOVERY_TIMEOUT)
    return [] if raw.startswith("[error]") else _container_names(raw)


def _container_names(raw: str) -> list[str]:
    return [line.strip() for line in raw.splitlines() if line.strip()]


def _collect_cmd(kind: str, name: str) -> list[str]:
    """Build a collection command. {name} is substituted only after
    collect_node has verified it against discover_node's own output --
    see collect_node's docstring. `kind` selects journalctl-by-unit,
    podman-logs, or journalctl-kernel; the journal dir / podman URL
    flags are added only when the matching proxy is configured.

    The name is passed as `--unit=<name>` and after a `--` separator
    respectively (audit M-4), never as a bare argument following a
    short flag. `-u foo` and `foo` are both positions where a value
    starting with `-` is read as an option instead: `-u --output=cat`
    or a container literally named `--help` would be interpreted by
    journalctl/podman rather than treated as a name. The attached form
    and the end-of-options marker remove that reading entirely.

    This is the second lock on a door that collect_node already
    bolted: a name only reaches here if it appeared verbatim in
    discovery output, and unit/container names don't normally start
    with a dash. What it defends is the case where discovery output is
    no longer trustworthy -- a hostile container name, or a proxy
    returning something the host didn't say -- which is exactly the
    assumption the validation rests on and therefore the one worth not
    resting the whole thing on.
    """
    if kind == "unit":
        cmd = ["journalctl"]
        if SYSADMIN_JOURNAL_DIR:
            cmd += ["-D", SYSADMIN_JOURNAL_DIR]
        return cmd + [f"--unit={name}", "--no-pager", "-n", str(SYSADMIN_MAX_LOG_LINES)]
    if kind == "container":
        cmd = ["podman"]
        if SYSADMIN_PODMAN_URL:
            cmd += ["--url", SYSADMIN_PODMAN_URL]
        return cmd + ["logs", "--tail", str(SYSADMIN_MAX_LOG_LINES), "--", name]
    if kind == "kernel":
        cmd = ["journalctl"]
        if SYSADMIN_JOURNAL_DIR:
            cmd += ["-D", SYSADMIN_JOURNAL_DIR]
        return cmd + ["-k", "--no-pager", "-n", str(SYSADMIN_MAX_LOG_LINES)]
    raise ValueError(f"unknown collect kind: {kind!r}")


def _subprocess_env() -> dict[str, str]:
    """Same minimal-env posture as tools/shell.py: no host env
    variables reach the subprocess except what's explicitly listed.
    DBUS_SYSTEM_BUS_ADDRESS is added only when SYSADMIN_DBUS_ADDRESS
    is configured, pointing busctl at the filtered proxy socket
    from deploy/forge-dbus-proxy.sh -- never the real system bus."""
    env = {"PATH": "/usr/local/bin:/usr/bin:/bin", "TERM": "dumb"}
    if SYSADMIN_DBUS_ADDRESS:
        env["DBUS_SYSTEM_BUS_ADDRESS"] = SYSADMIN_DBUS_ADDRESS
    return env


# The "/no_think" prefix below is NOT dead, however dead it looks.
# Qwen3.5 dropped the /think soft switch, and the router GBNF grammar
# (applied to every call, not just routing) already makes a reasoning
# block impossible -- so on paper the token buys nothing. Measured on
# 2026-08-16 with bench/no_think_ab.py, removing it made this model
# return the GOOD ANSWER example below instead of a real answer, twice,
# deterministically. Whatever it does at position 0 is not what its
# name says. Run that harness before touching it.
_SYNTHESIS_PROMPT = """/no_think
{today_line}
You are diagnosing a system/service problem using the logs gathered
for you below. Write a clear, natural diagnosis in plain text --
explain what is likely happening and propose a concrete fix. Write in
the same language as the question. Never claim you have executed or
will execute anything: you only read logs and propose, a human always
applies any fix by hand.

Question: {question}
{running_fact}
These logs are whatever `{source}` returned. They were gathered before
anyone read your question, so they may simply not contain the answer.
If they do not, say so plainly and say what you would need to look at
instead -- that is a correct answer here, and a confident diagnosis
built on logs that do not mention the subject is the one failure this
tool cannot recover from. Never treat the absence of an error in these
logs as evidence that nothing is wrong.

--- collected logs ({source}) ---
{log_block}
--- end of collected logs ---

Respond in plain text ONLY. Do NOT wrap your answer in JSON, and do
NOT return a {{"tool":...,"content":...}} object -- that format is
for a different system (a routing decision) and never applies here.

GOOD ANSWER (this is only an example of FORM AND TONE -- these exact
names, files and details are fictional placeholders, not real logs;
copying any of them into your own answer is always wrong, no matter
what the actual logs above say): Le service exemple-service.service
échoue au démarrage car la configuration référence un fichier
introuvable (/etc/exemple/manquant.conf). Je te propose de vérifier
que ce fichier existe et, si besoin, de le recréer avant de relancer
le service.
NEVER DO THIS: {{"tool":"chat","content":"..."}}

Now write your own diagnosis using ONLY what actually appears in the
collected logs above -- the words "exemple-service" and
"manquant.conf" must never appear in your answer, they belong to the
placeholder example only, never to a real one. Same plain format as
GOOD ANSWER, not the NEVER DO THIS shape. Be concise.
"""


def _run_fixed(cmd: list[str], timeout: int) -> str:
    """Run a command whose every element is either a fixed literal or
    a name already verified against discover_node's own output.
    Never shell=True, never a hand-built string -- same posture as
    tools/shell.py's allowlisted subprocess.run(parts, ...). Uses
    _subprocess_env() so DBUS_SYSTEM_BUS_ADDRESS (when configured)
    points busctl at the filtered proxy, not the host bus."""
    try:
        result = subprocess.run(
            cmd,
            check=False,
            capture_output=True,
            text=True,
            timeout=timeout,
            env=_subprocess_env(),
        )
    except FileNotFoundError:
        return f"[error] executable not found: {cmd[0]!r}"
    except subprocess.TimeoutExpired:
        return f"[error] command timed out after {timeout}s"
    except OSError as e:
        return f"[error] OS error: {e}"

    output = (result.stdout or result.stderr or "").strip()
    lines = output.splitlines()[:SYSADMIN_MAX_LOG_LINES]
    joined = "\n".join(lines) if lines else "[no output]"

    if result.returncode != 0:
        # The command RAN (no Python-level exception above) but the
        # target itself failed -- e.g. busctl unable to reach the bus,
        # podman unable to reach its socket. This must carry the same
        # "[error]" prefix as the exception-based cases above:
        # without it, a real production case slipped straight through
        # as if it were valid data. The case that taught this was
        # systemctl, back when discovery still used it: its two-line
        # failure message ("System has not been booted with
        # systemd...\nFailed to connect to bus...") got parsed as two
        # fake unit names ("System", "Failed") by _discover_node, and
        # podman's connection-refused text got parsed as a fake
        # container name the same way. Caught in production on
        # 2026-08-11. The systemctl path is gone; the failure mode it
        # exposed is not, which is why the guard stays.
        return f"[error] {cmd[0]} exited {result.returncode}: {joined}"

    return joined


def _discover_node(state: AgentState) -> AgentState:
    units_raw = _run_fixed(_DISCOVER_UNITS_CMD(), SYSADMIN_DISCOVERY_TIMEOUT)
    if units_raw.startswith("[error]"):
        # e.g. "executable not found: 'busctl'" -- systemd tooling
        # isn't necessarily present inside Forge's own container image.
        # Must not be parsed as a fake unit named "[error]".
        log.warning("sysadmin: unit discovery failed: %s", units_raw)
        units: list[str] = []
        dropped = 0
        state.context["discover_units_error"] = units_raw
    else:
        try:
            discovered = _parse_busctl_units(units_raw)
            units = _loggable(discovered)
            dropped = len(discovered) - len(units)
        except (json.JSONDecodeError, KeyError, IndexError, TypeError) as e:
            log.warning("sysadmin: failed to parse busctl ListUnits output: %s", e)
            units = []
            dropped = 0
            state.context["discover_units_error"] = (
                f"[error] failed to parse busctl output: {e}"
            )

    containers_raw = _run_fixed(_DISCOVER_CONTAINERS_CMD(), SYSADMIN_DISCOVERY_TIMEOUT)
    if containers_raw.startswith("[error]"):
        log.warning("sysadmin: container discovery failed: %s", containers_raw)
        containers: list[str] = []
        state.context["discover_containers_error"] = containers_raw
    else:
        containers = _container_names(containers_raw)

    state.context["units"] = units
    state.context["containers"] = containers
    log.event(
        "sysadmin.discover",
        units=len(units),
        devices_dropped=dropped,
        containers=len(containers),
    )
    return state


def _collect_node(state: AgentState) -> AgentState:
    """Picks exactly one collection target. target_hint must appear
    verbatim in discover_node's own units/containers list to be used
    at all -- an unrecognised hint silently falls back to kernel logs
    rather than being passed to a command, so there is no path from
    unvalidated router content to subprocess.run()."""
    target_hint = state.context.get("target_hint")
    units = state.context["units"]
    containers = state.context["containers"]

    if target_hint and target_hint in units:
        cmd = _collect_cmd("unit", target_hint)
        source = f"journalctl -u {target_hint}"
    elif target_hint and target_hint in containers:
        cmd = _collect_cmd("container", target_hint)
        source = f"podman logs {target_hint}"
    elif target_hint:
        # No fallback here any more. It used to drop to `journalctl -k`
        # and say nothing the model could see, and on run #83fc443e the
        # whole chain played out in one go: the podman proxy was down ->
        # containers came back empty -> the hint "forge-llm" matched
        # nothing -> kernel logs were collected -> the model wrote a
        # confident, entirely invented story about a variable blocking
        # searxng. Every step was individually reasonable.
        #
        # Kernel logs are a fine answer to "what is wrong with this
        # box?". They are never an answer to a question about a NAMED
        # service, so a run that reaches them with a name in hand has
        # already lost, and the only thing left to decide is whether it
        # loses loudly. It now stops here: no logs, no model call, no
        # opportunity to confabulate, and the report names what was
        # actually broken (usually discovery, not the service).
        state.context["target_missed"] = target_hint
        log.warning(
            "sysadmin: target_hint %r not found in discovery "
            "(%d units, %d containers), stopping instead of collecting kernel logs",
            target_hint,
            len(units),
            len(containers),
        )
        log.event("sysadmin.target_missed", target=target_hint)
        return state
    else:
        cmd = _collect_cmd("kernel", "")
        source = "journalctl -k"

    state.context["log_source"] = source
    collected = _run_fixed(cmd, SYSADMIN_COLLECT_TIMEOUT)
    state.context["collected_logs"] = collected

    # A failed collection is not a quiet log file. _run_fixed prefixes
    # "[error]" precisely so this is distinguishable, and until now
    # nothing distinguished it: the error text went into the prompt
    # under a "--- collected logs ---" header and the model was asked
    # to diagnose the service from it.
    #
    # The comment in _to_sub_steps used to argue that this stayed
    # useful, "the LLM diagnosing the meta-error itself". Two real runs
    # say otherwise. #7a29f59d and #7e0ed90c both got the podman
    # proxy's 403 refusal instead of logs, and both answered that the
    # container was crashing BECAUSE of that 403 -- a healthy container
    # (Up 6 minutes), a confident cause, 600+ characters of plausible
    # remediation for a fault that did not exist.
    #
    # Same shape as target_missed, so the same answer: the model is
    # never handed evidence about a different subject than the
    # question. The error is reported in code instead.
    if collected.startswith("[error]"):
        state.context["collect_failed"] = collected
        log.event("sysadmin.collect_failed", source=source, error=collected[:200])
        return state

    log.event("sysadmin.collect", source=source)
    return state


_RUNNING_FACT = """
FACT, established before you were called and not open to
reinterpretation: `{target}` WAS RUNNING when these logs were
collected. It appeared in `podman ps`, which lists running containers
only. Whatever the logs contain, this container was not down, had not
crashed, and was not failing to start. A question that assumes
otherwise is mistaken, and saying so is the correct answer.
"""

_RUNNING_FOOTER = (
    "\n\n---\n_État observé : `{target}` tournait au moment de la collecte "
    "(présent dans `podman ps`)._"
)


def _nothing_collected_node(state: AgentState) -> AgentState:
    """
    Report an empty collection, deterministically.

    The command ran, returned nothing, and there is no judgement to
    make: a diagnosis of zero lines is invention with extra steps.
    Until now this reached the synthesis with an empty block under a
    "--- collected logs ---" header, which is the same shape as
    handing the model a 403 and asking what is wrong with the service.

    This is the ONLY part of "the logs do not answer the question"
    that needs no model, and measuring the rest is what established
    that it is the only part available. See the module docstring.

    An empty log file is not a quiet system, and the message says so:
    `podman logs` on a container that has never written a line and
    `journalctl -u` on a window with no entries look identical from
    here, and neither is evidence that nothing is wrong.
    """
    source = state.context["log_source"]
    target = state.context.get("target_hint")
    subject = f"« {target} »" if target else "le système"

    state.final_output = (
        f"{non_answer.NOTHING_COLLECTED_PREFIX}`{source}` n'a rien renvoyé "
        f"pour {subject}. Il n'y a donc rien à diagnostiquer ici — et une "
        "sortie vide ne dit pas que tout va bien : elle dit que ce journal "
        "est vide, ce qui arrive aussi quand la cible écrit ailleurs ou "
        "quand la fenêtre interrogée ne couvre pas l'incident."
    )
    state.final_tool = "sysadmin"
    log.event("sysadmin.done", chars=len(state.final_output), collected=0)
    return state


def _collect_failed_node(state: AgentState) -> AgentState:
    """
    Report a failed collection, deterministically.

    Deliberately says what could not be read and stops. Naming the
    command matters more than it looks: the failure that produced this
    node was a proxy policy refusal that podman renders as an
    unmarshalling error, and the single most useful thing anyone could
    have been told is which command to run by hand.
    """
    source = state.context["log_source"]
    error = state.context["collect_failed"]
    target = state.context.get("target_hint")

    subject = f"« {target} »" if target else "le système"
    state.final_output = (
        f"{non_answer.COLLECT_FAILED_PREFIX}Je n'ai pas pu lire les logs de "
        f"{subject} : "
        f"la commande `{source}` a échoué.\n"
        f"{error}\n"
        "Tant que cette commande ne rend pas de logs, il n'y a rien à "
        "diagnostiquer — et ce message parle de la collecte, pas de l'état "
        "de la cible."
    )
    state.final_tool = "sysadmin"
    log.event("sysadmin.done", chars=len(state.final_output), collect_failed=True)
    return state


def _target_missed_node(state: AgentState) -> AgentState:
    """
    Report an unresolvable target, deterministically.

    Written entirely in code. This node exists because a model was
    asked to diagnose a service using logs from a different subsystem
    and did it -- fluently. There is no prompt for that; the answer is
    to not ask.
    """
    target = state.context["target_missed"]
    units = state.context["units"]
    containers = state.context["containers"]

    lines = [
        (
            f"{non_answer.TARGET_MISSED_PREFIX}« {target} » ne correspond à "
            f"aucune unité "
            f"systemd ni à aucun conteneur parmi ce que la découverte a "
            f"remonté ({len(units)} unités, {len(containers)} conteneurs)."
        )
    ]

    # Discovery failing is the interesting case and the common one: an
    # empty list means the proxy or busctl is down, not that the
    # machine has no services. Naming that turns "I could not find your
    # service" into "here is what to restart".
    for label, err_key, count in (
        ("unités systemd", "discover_units_error", len(units)),
        ("conteneurs", "discover_containers_error", len(containers)),
    ):
        err = state.context.get(err_key)
        if err:
            lines.append(f"La découverte des {label} a échoué : {err}")
        elif count == 0:
            lines.append(
                f"Aucun élément dans la liste des {label} — c'est "
                f"probablement la découverte qui est en panne, pas la cible."
            )

    close = difflib.get_close_matches(target, units + containers, n=3, cutoff=0.6)
    if close:
        lines.append("Cibles proches : " + ", ".join(close))

    state.final_output = "\n".join(lines)
    state.final_tool = "sysadmin"
    log.event("sysadmin.done", chars=len(state.final_output), target_missed=target)
    return state


def _clean_diagnosis_response(raw: str, log_block: str = "") -> str:
    """Same reasoning as review._clean_review_response and
    research._clean_synthesis_response (see forge/text_cleaning.py):
    this prompt asks for plain text, so the shared conditional-unwrap
    cleaner is reused here too, specifically to avoid the duplication
    drift already hit once between review and research in v3.10."""
    cleaned = strip_think_blocks(raw)

    unwrapped = try_unwrap_router_json(cleaned, source="sysadmin")
    if unwrapped is not None:
        cleaned = unwrapped

    if any(marker in cleaned for marker in _PROMPT_LEAK_MARKERS):
        log.warning("sysadmin: model echoed prompt instructions instead of answering")
        return "[error] Le modèle n'a pas généré de réponse exploitable. Réessayez."

    if any(fragment in cleaned for fragment in _EXAMPLE_LEAK_FRAGMENTS):
        log.warning(
            "sysadmin: model copied the GOOD ANSWER example verbatim "
            "instead of diagnosing the actual logs"
        )
        return "[error] Le modèle a recopié un exemple au lieu de générer un vrai diagnostic. Réessayez."

    if not cleaned:
        return "[error] Le modèle n'a pas généré de réponse. Réessayez."

    # Same guard review gained after run #b669174a. Not observed here
    # yet, and wired anyway: this graph already carries
    # _EXAMPLE_LEAK_FRAGMENTS, which is the same failure against a
    # different source text, and review/research last drifted apart
    # precisely because one of them was fixed alone (v3.10).
    if log_block and looks_like_a_copy(cleaned, log_block):
        log.warning("sysadmin: model echoed the logs instead of diagnosing them")
        return (
            "[error] Le modèle a recopié les logs au lieu de les analyser. Réessayez."
        )

    if len(cleaned) > _MAX_SYNTHESIS_OUTPUT_CHARS:
        cleaned = cleaned[:_MAX_SYNTHESIS_OUTPUT_CHARS].rstrip() + "…"

    return cleaned


def _truncate_log_block(log_block: str, budget: int) -> str:
    """Hard character cap independent of line count -- SYSADMIN_MAX_LOG_LINES
    alone isn't a safe context guarantee (line length varies a lot
    between journalctl/podman output). Keeps the END of the block:
    _run_fixed already returns at most the tail N lines via -n/--tail,
    so the most recent -- most relevant -- events are at the end."""
    if len(log_block) <= budget:
        return log_block
    return "…[troncated, showing the most recent output]…\n" + log_block[-budget:]


def _synthesize_node(state: AgentState) -> AgentState:
    question = (
        state.context.get("question")
        or "Diagnostique le problème et propose une solution."
    )
    source = state.context["log_source"]
    log_block = _truncate_log_block(
        state.context["collected_logs"], SYSADMIN_LOG_CHARS_BUDGET
    )

    # Run #be385d16: asked "pourquoi forge-embedding plante ?" about a
    # container that was up, the model read a routine llama.cpp
    # n_batch notice and concluded the service was crashing on "une
    # assertion ou une erreur interne NON AFFICHÉE" -- inventing the
    # evidence it lacked. Ninth time a wording fix has lost here.
    #
    # So this is not a wording fix. Discovery lists containers with
    # `podman ps`, no -a, which means presence in that list IS proof
    # the container was running. That fact is free, already collected,
    # and was being thrown away. It goes in the prompt as a FACT rather
    # than an instruction, and in the answer as a footer that holds
    # whatever the model decides to say.
    target = state.context.get("target_hint")
    running = bool(target) and target in state.context.get("containers", [])
    running_fact = _RUNNING_FACT.format(target=target) if running else ""

    prompt = _SYNTHESIS_PROMPT.format(
        today_line=today_line(),
        question=question,
        source=source,
        log_block=log_block,
        running_fact=running_fact,
    )

    # Language named in LAST position, and only when forge.lang is
    # sure -- same treatment recall got in the v3.12 dettes batch, for
    # the same reason: this prompt body is English prose, and it pulls
    # a French answer toward English all on its own. Appended rather
    # than templated in, so "last" cannot drift as the template grows.
    language_line = lang.line_for(question)

    log.event("sysadmin.llm_call", source=source, prompt_chars=len(prompt))
    try:
        # No grammar, so _grammar_for() supplies the ROUTER's. That is
        # deliberate -- see the header of forge/prose_grammar.py.
        raw = call_llm(prompt + language_line)
        log.event("sysadmin.raw_output", raw=raw)
        answer = _clean_diagnosis_response(raw, log_block)
        # The deterministic half. Naming the language in the prompt is
        # still a wording fix, and wording fixes have lost seven times
        # on this codebase. The retry re-sends the same prompt with a
        # different final line, so the KV prefix survives and only the
        # tail is recomputed.
        answer = lang.enforce(
            question,
            answer,
            retry=lambda line: _clean_diagnosis_response(
                call_llm(prompt + line), log_block
            ),
            enabled=ENFORCE_ANSWER_LANGUAGE,
        )
    except ProviderError as e:
        state.ok = False
        state.error = str(e)
        state.final_output = f"[error] LLM unavailable: {e}"
        return state

    if running and not answer.startswith("[error]"):
        answer += _RUNNING_FOOTER.format(target=target)

    state.final_output = answer
    state.final_tool = "sysadmin"
    log.event("sysadmin.done", chars=len(state.final_output), target_running=running)
    return state


#: The output-shaping half of the Harnais prompt -- what SHAPE the
#: answer must take, as opposed to what it may treat as true.
#:
#: forge/kernel/context_builder.py deliberately does not carry this.
#: The evidence half belongs with the World Model; this half belongs
#: next to _clean_diagnosis_response, which is what checks the model
#: obeyed it, and next to _EXAMPLE_LEAK_FRAGMENTS, which catches the
#: GOOD ANSWER example being copied instead of used. Splitting them the
#: other way would put the rule in one module and its enforcement in
#: another.
#:
#: Kept character-for-character in step with _SYNTHESIS_PROMPT's tail
#: on purpose: the same placeholder names, so the same leak detector
#: covers both. What it does NOT repeat is the evidence framing --
#: "these logs were gathered before you read the question", "never
#: treat the absence of an error as evidence" -- because the Context
#: Builder emits its own reading rules and two sets would disagree
#: about what the markers mean.
_CONTEXT_SHAPING = """
Respond in plain text ONLY. Do NOT wrap your answer in JSON, and do
NOT return a {"tool":...,"content":...} object -- that format is
for a different system (a routing decision) and never applies here.

GOOD ANSWER (this is only an example of FORM AND TONE -- these exact
names, files and details are fictional placeholders, not real
observations; copying any of them into your own answer is always
wrong, no matter what the context above actually says): Le service
exemple-service.service échoue au démarrage car la configuration
référence un fichier introuvable (/etc/exemple/manquant.conf). Je te
propose de vérifier que ce fichier existe et, si besoin, de le
recréer avant de relancer le service.
NEVER DO THIS: {"tool":"chat","content":"..."}

Now write your own answer using ONLY what actually appears above --
the words "exemple-service" and "manquant.conf" must never appear in
your answer. Same plain format as GOOD ANSWER. Be concise.
"""


def _harnais_path(state: AgentState) -> bool:
    """
    Whether this run takes route A: the Harnais instead of a log block.

    Only when NO target was named. A question about a named unit or
    container keeps the path it has -- validated collection, and the
    three refusals written in code when that validation fails. That
    boundary is not caution, it is measured: bench/context_builder_ab.py
    asked this model "pourquoi forge-llm plante ?" against a context
    stating the container could not be observed, and got back "plante
    CAR le socket de Podman n'existe pas" -- the instrument's failure
    returned as the phenomenon's cause, stable over four runs. A named
    target reaches _target_missed_node long before any of that, and
    that is where it stays.
    """
    return SYSADMIN_USE_HARNAIS and not state.context.get("target_hint")


def _observe_node(state: AgentState) -> AgentState:
    """
    Ask every Harnais collector what it can see, and record it.

    This runs a second `podman ps` -- _discover_node has already run
    one. Left as it is rather than threaded through: the collectors own
    their observation by design (a collector that took someone else's
    list would inherit that list's failure modes silently), and the
    duplicate is one proxied call against a local socket. The day it
    matters, the fix is to drop discover from this path, not to share
    its output.
    """
    world = InMemoryWorldModel()
    observations = harnais.observe(harnais.default_collectors())
    for observation in observations:
        world.record_observation(observation)

    state.context["world"] = world
    failed = [o.collector for o in observations if o.failed]
    log.event(
        "sysadmin.observe",
        collectors=len(observations),
        failed=failed,
        facts=sum(len(o.facts) for o in observations),
    )
    return state


def _observed_nothing(state: AgentState) -> bool:
    """True when not one collector produced a single Fact."""
    world = state.context.get("world")
    if world is None:
        return False
    return not any(world.current_state(domain) for domain in MVP_DOMAINS)


def _nothing_observed_node(state: AgentState) -> AgentState:
    """
    Report a total observation failure, deterministically.

    Written in code because the alternative was measured and is worse.
    bench/context_builder_ab.py removed the failing command's error text
    from the context, on the theory that a cause cannot be built out of
    a string that is not there. The model reached for the next nearest
    facts instead and declared HEALTHY ones guilty -- "plante car la
    charge CPU est élevée (0.9 sur 1 minute)", stable over three runs.

    Asked why something is wrong, this model returns a cause whatever
    the context holds; removing a candidate yields the next candidate,
    never a refusal. So when there is nothing to reason from, it is not
    asked. The error text still reaches the reader -- it reaches them
    from here, which is the same split _collect_failed_node already
    makes, and the same reason it makes it.
    """
    world = state.context["world"]
    lines = [
        (
            f"{non_answer.NOTHING_OBSERVED_PREFIX}Je n'ai rien pu observer sur "
            "cette machine : aucune source n'a répondu, donc il n'y a aucun "
            "fait sur lequel appuyer un diagnostic. Ce message parle de "
            "l'observation, pas de l'état de la machine — elle va peut-être "
            "très bien."
        )
    ]
    for domain in MVP_DOMAINS:
        error = world.observation_error(domain)
        if error:
            lines.append(f"- {domain} : {error}")

    state.final_output = "\n".join(lines)
    state.final_tool = "sysadmin"
    log.event("sysadmin.done", chars=len(state.final_output), observed_nothing=True)
    return state


def _context_synthesize_node(state: AgentState) -> AgentState:
    """One diagnosis, from the Context Builder's text rather than a log block."""
    question = (
        state.context.get("question")
        or "Diagnostique le problème et propose une solution."
    )
    context = ContextBuilder(state.context["world"]).build_for(
        question, SYSADMIN_CONTEXT_BUDGET_TOKENS
    )
    state.context["harnais_context"] = context

    # "/no_think" stays at position 0, where it was measured to matter
    # -- see the note above _SYNTHESIS_PROMPT. The Context Builder does
    # not emit it precisely so this stays true wherever it is called.
    prompt = "/no_think\n" + context + "\n" + _CONTEXT_SHAPING
    language_line = lang.line_for(question)

    log.event("sysadmin.llm_call", source="harnais", prompt_chars=len(prompt))
    try:
        raw = call_llm(prompt + language_line)
        log.event("sysadmin.raw_output", raw=raw)
        answer = _clean_diagnosis_response(raw)
        answer = lang.enforce(
            question,
            answer,
            retry=lambda line: _clean_diagnosis_response(call_llm(prompt + line)),
            enabled=ENFORCE_ANSWER_LANGUAGE,
        )
    except ProviderError as e:
        state.ok = False
        state.error = str(e)
        state.final_output = f"[error] LLM unavailable: {e}"
        return state

    state.final_output = answer
    state.final_tool = "sysadmin"
    log.event("sysadmin.done", chars=len(state.final_output), source="harnais")
    return state


def build() -> Graph:
    g = Graph("sysadmin", max_steps=6)
    g.add_node("discover", _discover_node)
    g.add_node("collect", _collect_node)
    g.add_node("target_missed", _target_missed_node, answers=False)
    g.add_node("collect_failed", _collect_failed_node, answers=False)
    g.add_node("nothing_collected", _nothing_collected_node, answers=False)
    g.add_node("synthesize", _synthesize_node)
    g.add_node("observe", _observe_node)
    g.add_node("nothing_observed", _nothing_observed_node, answers=False)
    g.add_node("context_synthesize", _context_synthesize_node)

    # Route A, and only for a question that names no target -- see
    # _harnais_path. Declared BEFORE the edge to collect, because Graph
    # takes the first matching edge, and the one to collect is
    # unconditional.
    g.add_edge("discover", "observe", condition=_harnais_path)
    g.add_edge("discover", "collect")

    # Nothing observed at all is a refusal written in code, not a
    # thinner prompt -- see _nothing_observed_node for the measurement
    # that settled it.
    g.add_edge("observe", "nothing_observed", condition=_observed_nothing)
    g.add_edge("observe", "context_synthesize")
    # Order matters -- Graph takes the first matching edge.
    g.add_edge(
        "collect",
        "target_missed",
        condition=lambda s: bool(s.context.get("target_missed")),
    )
    g.add_edge(
        "collect",
        "collect_failed",
        condition=lambda s: bool(s.context.get("collect_failed")),
    )
    g.add_edge(
        "collect",
        "nothing_collected",
        condition=lambda s: not (s.context.get("collected_logs") or "").strip(),
    )
    g.add_edge("collect", "synthesize")

    return g


def _format_discovered_list(names: list[str], max_shown: int = 8) -> str:
    """Names, not just a count -- capped so a host with dozens of
    active units doesn't produce an unreadable wall of text in the
    UI's expanded step detail."""
    if not names:
        return "aucun"
    shown = ", ".join(names[:max_shown])
    if len(names) > max_shown:
        shown += f", … (+{len(names) - max_shown})"
    return shown


def _to_sub_steps(state: AgentState) -> list[dict]:
    """Turn this run's internal graph trace (already recorded node by
    node by graph.py's Node.execute) into small, human-readable steps
    for the UI -- see forge/subtrace.py's docstring for why this is a
    separate publish rather than a widened tool contract."""
    units = state.context.get("units", [])
    containers = state.context.get("containers", [])
    units_error = state.context.get("discover_units_error")
    containers_error = state.context.get("discover_containers_error")
    collected_logs = state.context.get("collected_logs", "")
    collect_error = collected_logs if collected_logs.startswith("[error]") else None
    world = state.context.get("world")
    any_domain_unobserved = world is not None and any(
        not world.current_state(d) for d in MVP_DOMAINS
    )

    def discover_detail() -> str:
        # "unités" and not "services": what ListUnits returns is every
        # unit type systemd knows, and the line under this label has
        # held mounts, timers and targets since the day it was written.
        # It also held four device nodes out of eight names, which is
        # fixed one commit earlier -- this is the half of that fault
        # the filter does not reach.
        units_part = (
            f"unités : erreur ({units_error})"
            if units_error
            else f"unités : {_format_discovered_list(units)}"
        )
        containers_part = (
            f"containers : erreur ({containers_error})"
            if containers_error
            else f"containers : {_format_discovered_list(containers)}"
        )
        return f"{units_part} | {containers_part}"

    def collect_detail() -> str:
        missed = state.context.get("target_missed")
        if missed:
            return f"cible « {missed} » introuvable, aucun log collecté"
        source = state.context.get("log_source", "?")
        if collect_error:
            return f"source : {source} | erreur : {collect_error}"
        return f"source : {source}"

    def observe_detail() -> str:
        world = state.context.get("world")
        if world is None:
            return "aucune observation"
        seen, missing = [], []
        for domain in MVP_DOMAINS:
            facts = world.current_state(domain)
            (seen if facts else missing).append(
                f"{domain} ({len(facts)})" if facts else domain
            )
        parts = [f"observé : {', '.join(seen)}" if seen else "observé : rien"]
        if missing:
            # Named, never omitted. A domain that silently vanishes from
            # this line reads as one that had nothing to report, which
            # is the distinction the whole Harnais exists to keep.
            parts.append(f"non observé : {', '.join(missing)}")
        return " | ".join(parts)

    details = {
        "discover": discover_detail,
        "collect": collect_detail,
        "observe": observe_detail,
        "nothing_observed": lambda: "aucune source n'a répondu",
        "context_synthesize": lambda: (
            f"diagnostic généré depuis {len(state.context.get('harnais_context', ''))} "
            f"caractères de contexte ({len(state.final_output or '')} caractères)"
        ),
        "collect_failed": lambda: (
            f"collecte échouée : {state.context.get('collect_failed', '')[:120]}"
        ),
        "target_missed": lambda: (
            f"« {state.context.get('target_missed')} » absent de la découverte"
        ),
        "synthesize": lambda: (
            f"diagnostic généré ({len(state.final_output or '')} caractères)"
        ),
    }
    steps = subtrace.from_state(state, details)
    # sysadmin is the one graph whose per-step `ok` is not simply
    # state.ok: discover and collect can fail partially while the run
    # as a whole still finishes. from_state deliberately does not know
    # that, so it is overridden here rather than made a parameter no
    # other graph would pass.
    for step, ts in zip(steps, state.trace, strict=True):
        step["ok"] = (
            False
            if ts.decision_tool == "discover" and (units_error or containers_error)
            else False
            if ts.decision_tool == "collect"
            and (collect_error or state.context.get("target_missed"))
            else False
            if ts.decision_tool == "observe" and any_domain_unobserved
            else ts.tool_ok
        )
    return steps


def run(target_hint: str | None, question: str | None) -> str:
    """Discover active units/containers, collect logs for target_hint
    (or fall back to kernel logs), and synthesize one diagnosis."""
    state = build().run(
        target_hint or "",
        initial_context={"target_hint": target_hint, "question": question},
    )
    subtrace.publish(_to_sub_steps(state))
    return state.final_output or ""
